server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jarryhu/springcloud-test.git
          searchPaths: config
          username: jarryhu
          password: Jerryhu780910
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/